### ISSUE TITLE
Needs update?

### ISSUE THREAD

**Issue by davedawkins** [MangelMaxime/Elmish.Canvas#4]
I'm having a hard time getting this to build (macos). I've started looking into what might be wrong, and these are two things I see immediately:
- Mouse.fs missing according to elmish_demos.fsproj
- `[<Pojo>]` seems to have just disappeared from Fable, despite being mentioned in a few online tutorials. I'm assuming it became obsolete (?)

@MangelMaxime I see you do lots of wonderful things with Fable; if you're still active I'd appreciate you checking this project out and seeing if at least from your point of view it's up to date with latest Fable ecosystem. 

Many thanks

**Comment by MangelMaxime** [comment]
Hello @davedawkins, 

if this projet use `[<Pojo>]` then it definitly use an old version of Fable (version 1) because it has been removed in Fable 2.

I will try to take look at the project and see how hard it is to upgrade it to latest version.

**Comment by MangelMaxime** [comment]
I updated `master` branch and `feature/standalone-impl`.

Please note that this project was experimentation some I am not sure how usable it is.

**Comment by davedawkins** [comment]
Thank you! I appreciate it was experimental, but it has great educational value for newcomers (like me) and it's worth keeping up-to-date. I see Elm projects that just don't work anymore, it doesn't look good. Thank you again.
